services:
  frontend:
    build: 
      context: ./Frontend/
      dockerfile: Dockerfile
    container_name: elo-leaderboard-frontend
    networks:
      - elo-leaderboard-network
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

  backend:
    build: 
      context: ./Backend/
      dockerfile: Dockerfile
    container_name: elo-leaderboard-backend
    networks:
      - elo-leaderboard-network
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build: 
      context: ./Nginx/
      dockerfile: Dockerfile.prod
    container_name: elo-leaderboard-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - elo-leaderboard-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
  
networks:
  elo-leaderboard-network:
    driver: bridge